language: node_js
node_js: 6

services:
    - docker

before_install:
    - docker --version # TODO: Waiting for Docker 1.13 (https://github.com/docker/docker/pull/26839#issuecomment-262341921)
    - docker build -t bugyik/apib2json:${TRAVIS_COMMIT} .
    - docker run --detach --entrypoint=/bin/sh --name ${TRAVIS_COMMIT} bugyik/apib2json:${TRAVIS_COMMIT} -c 'while true; do sleep 1; done;'
    - docker exec -it ${TRAVIS_COMMIT} npm install
    - npm install --global coveralls@2.11.15

script:
    - docker exec -it ${TRAVIS_COMMIT} npm run --silent lint
    - docker exec -it ${TRAVIS_COMMIT} npm run --silent coverage
    - docker exec -it ${TRAVIS_COMMIT} sh -c "cat coverage/lcov.info" | coveralls

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        VERSION=$(git describe | sed 's/^v//');
        echo $VERSION;
        docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
        docker tag bugyik/apib2json:${TRAVIS_COMMIT} bugyik/apib2json:${VERSION};
        docker tag bugyik/apib2json:${TRAVIS_COMMIT} bugyik/apib2json:latest;
        docker push bugyik/apib2json:${VERSION};
        docker push bugyik/apib2json:latest;
        fi
